# Generated by Django 5.2.4 on 2025-10-31 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdrop', '0005_remove_order_vendor_order_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Vendor',
            new_name='vendor',
        ),
 # migrations.RemoveField(
 #    model_name='vendor',
#     name='address',),
        
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotdrop.vendor')),
            ],
        ),
    ]
