# Generated by Django 5.2.4 on 2025-11-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotdrop', '0008_remove_vendor_address_alter_vendor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
    ]
